name: Test Java Code Examples against Atlas

on:
  pull_request:
    paths:
      - "java/src/main/java/**"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Install dependencies with Maven
        run: |
          cd java/
          mvn install -DskipTests
      - name: Test with Maven
        env:
          ATLAS_CONNECTION_STRING: ${{ secrets.JAVA_CONNECTION_STRING }}
        run: |
          echo "ATLAS_CONNECTION_STRING is set to $ATLAS_CONNECTION_STRING"
          export ENV="Atlas"
          cd java/
          mvn test
