name: Test Java Code Examples against Atlas

on:
  pull_request_target:
    types: [opened, synchronize]
    paths:
      - "java/src/main/java/**"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Check access
        if: ${{ github.event.pull_request.author_association != 'COLLABORATOR' }}
        run: |
          echo "Event not triggered by a collaborator."
          exit 1
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Install dependencies with Maven
        run: |
          cd java/
          mvn install -DskipTests
      - name: Test with Maven
        env:
          ATLAS_CONNECTION_STRING: ${{ secrets.JAVA_CONNECTION_STRING }}
        run: |
          echo "ATLAS_CONNECTION_STRING is set to ${{ secrets.JAVA_CONNECTION_STRING }}"
          export ENV="Atlas"
          cd java/
          mvn test
